### ISSUE TITLE
Leaflet errs while fitting bounds and stops loading

### ISSUE THREAD

**Issue by plant99** [ironmaps/mapinurl#1]
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
leaflet.js:5 Uncaught Error: Bounds are not valid.
    at e.fitBounds (leaflet.js:5:29198)
    at index.js:48:9
fitBounds @ leaflet.js:5
(anonymous) @ index.js:48
DevTools failed to load source map: Could not load content for https://ironmaps.github.io/mapinurl/scripts/leaflet.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

@funnelferry came across this, trying to reproduce.

**Comment by plant99** [comment]
Fixed with https://github.com/ironmaps/mapinurl/commit/64a69f2df5b00125d27ee476a497990a1b428e83
